/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan Daniel Cavero Tovar
 */
public class PnlPregunta extends javax.swing.JPanel {

    /**
     * Creates new form PnlPregunta
     */
    public PnlPregunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iconprin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Frecuencia baja, media y alta?", "¿Son peligrosas las ondas de los celulares?", "¿Radiaciones electromagnéticas?", "Recomendaciones preventivas" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INFORMACION");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("El creciente desarrollo y masificación de las tecnologías ha \ngenerado una preocupación general acerca de los posibles\nefectos nocivos de los dispositivos tecnológicos en la salud \nhumana. Ello se debe principalmente a una falta de una\ninvestigación rigurosa y a una percepción del riesgo \ndistorsionada.\nLas tecnologías producen campos de frecuencia intermedia (FI), con\nfrecuencias de 300 Hz a 10 MHz, y campos de radiofrecuencia (RF),\ncon frecuencias de 10 MHz a 300 GHz. Los efectos de los campos\nelectromagnéticos sobre el organismo no sólo dependen de su\nintensidad sino también de su frecuencia y energía. No obstante,\npara producir estos efectos, los campos exteriores al organismo deben\nser muy intensos, mayor a los presentes habitualmente en el medio.");
        jScrollPane1.setViewportView(jTextArea1);

        iconprin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconprin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pnlpre0.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconprin))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(iconprin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int val = jComboBox1.getSelectedIndex();
        switch (val) {
            case 0:
                jTextArea1.setFont(new Font("TimesRoman", Font.PLAIN, 14));
                jTextArea1.setText("El creciente desarrollo y masificación de las tecnologías ha \n"
                        + "generado una preocupación general acerca de los posibles\n"
                        + "efectos nocivos de los dispositivos tecnológicos en la salud \n"
                        + "humana. Ello se debe principalmente a una falta de una\n"
                        + "investigación rigurosa y a una percepción del riesgo \n"
                        + "distorsionada.\n"
                        + "Las tecnologías producen campos de frecuencia intermedia (FI), con" + "\n"
                        + "frecuencias de 300 Hz a 10 MHz, y campos de radiofrecuencia (RF)," + "\n"
                        + "con frecuencias de 10 MHz a 300 GHz. Los efectos de los campos" + "\n"
                        + "electromagnéticos sobre el organismo no sólo dependen de su" + "\n"
                        + "intensidad sino también de su frecuencia y energía. No obstante," + "\n"
                        + "para producir estos efectos, los campos exteriores al organismo deben" + "\n"
                        + "ser muy intensos, mayor a los presentes habitualmente en el medio.");
                iconprin.setIcon(new ImageIcon(getClass().getResource("/Img/pnlpre0.jpg")));
                break;
            case 1:
                jTextArea1.setFont(new Font("TimesRoman", Font.PLAIN, 14));
                jTextArea1.setText("La principal preocupación concierne al uso de aparatos celulares y las" + "\n"
                        + "antenas de telefonía que se encuentran a lo largo y ancho de las" + "\n"
                        + "ciudades; sin embargo aún no existe evidencia científica suficiente para" + "\n"
                        + "riesgo a la salud humana.\n" + "\n"
                        + "Ferrán Tarrasa, jefe de Ingeniería de la Planta de la Central Nuclear de" + "\n"
                        + "Ascó en Tarragona España, afirmó durante una conferencia sobre las" + "\n"
                        + "ondas electromagnéticas que las ondas emitidas por los celulares y" + "\n"
                        + "por las antenas de telefonía no son ionizantes, es decir, no se ha" + "\n"
                        + "comprobado que tengan efectos genotóxicos porque no afectalas" + "\n"
                        + "cadenas de ADN conmaterial genético, ni tiene incidencia en el" + "\n"
                        + "desarrollo fetal, el sistema endocrino o el sistema inmune," + "\n"
                        + " tampoco se ha encontrado una relación directa entre las ondas" + "\n"
                        + " electromagnéticas y el cáncer.");
                iconprin.setIcon(new ImageIcon(getClass().getResource("/Img/pnlpre1.png")));
                break;
            case 2:
                jTextArea1.setFont(new Font("TimesRoman", Font.PLAIN, 14));
                jTextArea1.setText("• La radiación electromagnética esta formada por la combinación de" + "\n"
                        + "campos eléctricos y magnéticos, que se propagan a través del espacio"+"\n"
                        + "en forma de ondas portadoras de energía"+"\n" + "\n"
                        + "• Las ondas electromagnéticas tienen las vibraciones perpendiculares" + "\n"
                        + "a la dirección de propagación de la onda. Por tal motivo, se las clasifica"+ "\n"
                        +"entre las ondas transversales."+"\n"+"\n"
                        + "• Las ondas electromagnéticas viajan a través del espacio, y no"+ "\n"
                        + "necesitan de un medio material para propagarse.");
                iconprin.setIcon(new ImageIcon(getClass().getResource("/Img/pnlpre2.png")));
                break;
            case 3:
                jTextArea1.setFont(new Font("TimesRoman", Font.PLAIN, 14));
                jTextArea1.setText("• Reubica los muebles, sobre todo aquellos más frecuentados, para" + "\n"
                        + "alejarlos de los emisores de CEM como luz fluorescente y calentadores.\n" + "\n"
                        + "• Cuando vayas a comprar aparatos electrónicos, examina con un"+ "\n"
                        + "medidor para determinar cuáles tienen menor emisión electromagnética.\n" + "\n"
                        + "• Consulta a un electricista calificado para determinar la pérdida de"+ "\n"
                        + "radiaciones en tu hogar\n" + "\n"
                        + "• Si sospechas que tu casa está ubicada en una zona de alta exposición" + "\n"
                        + "electromagnética, debido a su cercaníacon alguna antena telefónica u" + "\n" + "tomen las medidas necesarias.\n" + "\n"
                        + "• Disminuye el uso de dispositivos inalámbricos como celulares y"+ "\n"
                        + "computadores portátiles.");
                iconprin.setIcon(new ImageIcon(getClass().getResource("/Img/pnlpre3.jpg")));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * ¿Frecuencia baja, media y alta? ¿Son peligrosas las ondas de los
     * celulares? ¿Radiaciones electromagnéticas? Recomendaciones preventivas
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconprin;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
