/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Forms.*;

import Data.Tabla;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Juan Daniel Cavero Tovar
 */
public class PnlTabData extends javax.swing.JPanel {

    /**
     * Creates new form PnlTabData
     */
    public PnlTabData() {
        initComponents();
        show_table();
    }

    public ArrayList<Tabla> tablalistado() {
        ArrayList<Tabla> tablalistado = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/dbwaveselectronic";
            String user = "root";
            String contra = "";
            Connection con = DriverManager.getConnection(url, user, contra);
            String queryfirst = "SELECT * FROM dispoelectronicos Order by modelo";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryfirst);
            Tabla tablita;

            while (rs.next()) {
                tablita = new Tabla(rs.getString("modelo"), rs.getString("diselec"), rs.getDouble("tresdis"), rs.getDouble("treintadis"), rs.getDouble("unmdis"), rs.getInt("campele"));
                tablalistado.add(tablita);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return tablalistado;
    }

    private void show_table() {
        ArrayList<Tabla> list = tablalistado();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] Row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            Row[0] = list.get(i).getModelo();
            Row[1] = list.get(i).getDiselec();
            Row[2] = list.get(i).getTresdis();
            Row[3] = list.get(i).getTreintadis();
            Row[4] = list.get(i).getUnmdis();
            Row[5] = list.get(i).getCampele();

            model.addRow(Row);
        }

    }

    public ArrayList<Tabla> busqueda() {
        ArrayList<Tabla> busqueda = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/dbwaveselectronic";
            String user = "root";
            String contra = "";
            Connection con = DriverManager.getConnection(url, user, contra);
            String queryfirst = "SELECT * FROM `dispoelectronicos` WHERE diselec='" + valor + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryfirst);
            Tabla tablita;

            while (rs.next()) {
                tablita = new Tabla(rs.getString("modelo"), rs.getString("diselec"), rs.getDouble("tresdis"), rs.getDouble("treintadis"), rs.getDouble("unmdis"), rs.getInt("campele"));
                busqueda.add(tablita);
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return busqueda;
    }

    public void show_search() {
        ArrayList<Tabla> list = busqueda();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Object[] Row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            Row[0] = list.get(i).getModelo();
            Row[1] = list.get(i).getDiselec();
            Row[2] = list.get(i).getTresdis();
            Row[3] = list.get(i).getTreintadis();
            Row[4] = list.get(i).getUnmdis();
            Row[5] = list.get(i).getCampele();

            model.addRow(Row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 480));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Secador de Pelo", "Aspiradora", "Microondas", "Horno eléctrico", "Ordenador" }));

        jButton1.setText("BUSQUEDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("SELECCIONAR DISPOSITIVO ELECTRONICO:");
        jTextField1.setBorder(null);

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo", "Dispositivo", "A 3 cm (µT)", "A 30 cm (µT)", "A 1 m (µT) ", "A (V/m) a 30 cm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(24);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setMinWidth(100);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(3).setMinWidth(100);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents
String valor;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        int val = jComboBox1.getSelectedIndex();
        switch (val) {
            case 0:
                tablalistado().clear();
                show_table();
                break;
            case 1:
                valor = "Secador de Pelo";
                busqueda().clear();
                show_search();
                break;
            case 2:
                valor = "Aspiradora";
                busqueda().clear();
                show_search();
                break;
            case 3:
                valor = "Microondas";
                busqueda().clear();
                show_search();
                break;
            case 4:
                valor = "Horno eléctrico";
                busqueda().clear();
                show_search();
                break;
            default:
                valor = "Ordenador";
                busqueda().clear();
                show_search();
                break;
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        /*
    public static String model;
    public static String dispo;
    public static double trescm;
    public static double treintacm;
    public static double unm;
    public static int  campoele;
         */
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selection = jTable1.getSelectedRow();
        MenuOperation.model = model.getValueAt(selection, 0).toString();
        MenuOperation.dispo = model.getValueAt(selection, 1).toString();
        MenuOperation.trescm = model.getValueAt(selection, 2).toString();
        MenuOperation.treintacm = model.getValueAt(selection, 3).toString();
        MenuOperation.unm = model.getValueAt(selection, 4).toString();
        MenuOperation.campoele = model.getValueAt(selection, 5).toString();

        MenuOperation ope = new MenuOperation();
        ope.setVisible(true);


    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
